services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile.prod
    container_name: tic-tac-toe-backend
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env.production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - backend-network
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: tic-tac-toe-redis
    restart: unless-stopped
    networks:
      - backend-network
    volumes:
      - redis_data:/data

networks:
  backend-network:
    driver: bridge

volumes:
  redis_data: