services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      - FLASK_ENV=development
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    restart: unless-stopped
